config/routes.rb
Doctor::Application.routes.draw do
  get "index/create"

  get "index/edit"

  get "index/delete"

  resources :illnesses

  resources :symptoms

end

app/models/illness.rb
class Illness < ActiveRecord::Base
	has_and_belongs_to_many :symptoms
  attr_accessible :definition, :name, :symtom_id
end

app/models/symptom.rb
class Symptom < ActiveRecord::Base
	has_and_belongs_to_many :illnesses
  attr_accessible :definition, :illness_id, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/illnesses_controller.rb
class IllnessesController < ApplicationController
  # GET /illnesses
  # GET /illnesses.json
  def index
    @illnesses = Illness.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @illnesses }
    end
  end

  # GET /illnesses/1
  # GET /illnesses/1.json
  def show
    @illness = Illness.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @illness }
    end
  end

  # GET /illnesses/new
  # GET /illnesses/new.json
  def new
    @illness = Illness.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @illness }
    end
  end

  # GET /illnesses/1/edit
  def edit
    @illness = Illness.find(params[:id])
    @symptoms = Symptom.find(:all, :order => "nom")
  end

  # POST /illnesses
  # POST /illnesses.json
  def create
    @illness = Illness.new(params[:illness])

    respond_to do |format|
      if @illness.save
        format.html { redirect_to @illness, notice: 'Illness was successfully created.' }
        format.json { render json: @illness, status: :created, location: @illness }
      else
        format.html { render action: "new" }
        format.json { render json: @illness.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /illnesses/1
  # PUT /illnesses/1.json
  def update
    @illness = Illness.find(params[:id])

    respond_to do |format|
      if @illness.update_attributes(params[:illness])
        format.html { redirect_to @illness, notice: 'Illness was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @illness.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /illnesses/1
  # DELETE /illnesses/1.json
  def destroy
    @illness = Illness.find(params[:id])
    @illness.destroy

    respond_to do |format|
      format.html { redirect_to illnesses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def create
  end

  def edit
  end

  def delete
  end
end

app/controllers/symptoms_controller.rb
class SymptomsController < ApplicationController
  # GET /symptoms
  # GET /symptoms.json
  def index
    @symptoms = Symptom.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @symptoms }
    end
  end

  # GET /symptoms/1
  # GET /symptoms/1.json
  def show
    @symptom = Symptom.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @symptom }
    end
  end

  # GET /symptoms/new
  # GET /symptoms/new.json
  def new
    @symptom = Symptom.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @symptom }
    end
  end

  # GET /symptoms/1/edit
  def edit
    @symptom = Symptom.find(params[:id])
    @illnesses = Illness.find(:all, :order => "nom")
  end

  # POST /symptoms
  # POST /symptoms.json
  def create
    @symptom = Symptom.new(params[:symptom])

    respond_to do |format|
      if @symptom.save
        format.html { redirect_to @symptom, notice: 'Symptom was successfully created.' }
        format.json { render json: @symptom, status: :created, location: @symptom }
      else
        format.html { render action: "new" }
        format.json { render json: @symptom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /symptoms/1
  # PUT /symptoms/1.json
  def update
    @symptom = Symptom.find(params[:id])

    respond_to do |format|
      if @symptom.update_attributes(params[:symptom])
        format.html { redirect_to @symptom, notice: 'Symptom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @symptom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /symptoms/1
  # DELETE /symptoms/1.json
  def destroy
    @symptom = Symptom.find(params[:id])
    @symptom.destroy

    respond_to do |format|
      format.html { redirect_to symptoms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/illnesses_helper.rb
module IllnessesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/symptoms_helper.rb
module SymptomsHelper
end

app/views/illnesses/_form.html.erb
<%= form_for(@illness) do |f| %>
  <% if @illness.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@illness.errors.count, "error") %> prohibited this illness from being saved:</h2>

      <ul>
      <% @illness.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :definition %><br />
    <%= f.text_area :definition %>
  </div>

  <select data-placeholder="Choose a Category..." class="chzn-select" multiple style="width:350px;" tabindex="4">
    <option value=""></option>
    <% Symptom.all.each do |symptom| %>  
      <option value="<%= symptom.id %>"><%= symptom.name %></option> 
    <% end %> 
  </select>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/illnesses/edit.html.erb
<h1>Editing illness</h1>

<%= render 'form' %>

<%= link_to 'Show', @illness %> |
<%= link_to 'Back', illnesses_path %>

app/views/illnesses/index.html.erb
<h1>Listing illnesses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Definition</th>
    <th>Symtom</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @illnesses.each do |illness| %>
  <tr>
    <td><%= illness.name %></td>
    <td><%= illness.definition %></td>
    <td><%= illness.symtom_id %></td>
    <td><%= link_to 'Show', illness %></td>
    <td><%= link_to 'Edit', edit_illness_path(illness) %></td>
    <td><%= link_to 'Destroy', illness, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Illness', new_illness_path %>

app/views/illnesses/new.html.erb
<h1>New illness</h1>

<%= render 'form' %>

<%= link_to 'Back', illnesses_path %>

app/views/illnesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @illness.name %>
</p>

<p>
  <b>Definition:</b>
  <%= @illness.definition %>
</p>

<p>
  <b>Symtom:</b>
  <%= @illness.symtom_id %>
</p>


<%= link_to 'Edit', edit_illness_path(@illness) %> |
<%= link_to 'Back', illnesses_path %>

app/views/index/create.html.erb
<h1>Index#create</h1>
<p>Find me in app/views/index/create.html.erb</p>

app/views/index/delete.html.erb
<h1>Index#delete</h1>
<p>Find me in app/views/index/delete.html.erb</p>

app/views/index/edit.html.erb
<h1>Index#edit</h1>
<p>Find me in app/views/index/edit.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doctor</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/symptoms/_form.html.erb
<%= form_for(@symptom) do |f| %>
  <% if @symptom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@symptom.errors.count, "error") %> prohibited this symptom from being saved:</h2>

      <ul>
      <% @symptom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :definition %><br />
    <%= f.text_area :definition %>
  </div>
  <div class="field">
    <%= f.label :illness_id %><br />
    <%= f.number_field :illness_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/symptoms/edit.html.erb
<h1>Editing symptom</h1>

<%= render 'form' %>

<%= link_to 'Show', @symptom %> |
<%= link_to 'Back', symptoms_path %>

app/views/symptoms/index.html.erb
<h1>Listing symptoms</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Definition</th>
    <th>Illness</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @symptoms.each do |symptom| %>
  <tr>
    <td><%= symptom.name %></td>
    <td><%= symptom.definition %></td>
    <td><%= symptom.illness_id %></td>
    <td><%= link_to 'Show', symptom %></td>
    <td><%= link_to 'Edit', edit_symptom_path(symptom) %></td>
    <td><%= link_to 'Destroy', symptom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Symptom', new_symptom_path %>

app/views/symptoms/new.html.erb
<h1>New symptom</h1>

<%= render 'form' %>

<%= link_to 'Back', symptoms_path %>

app/views/symptoms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @symptom.name %>
</p>

<p>
  <b>Definition:</b>
  <%= @symptom.definition %>
</p>

<p>
  <b>Illness:</b>
  <%= @symptom.illness_id %>
</p>


<%= link_to 'Edit', edit_symptom_path(@symptom) %> |
<%= link_to 'Back', symptoms_path %>